# ==========================================================
#  Alacritty 配置  ––  Everforest 配色（6 套，已修正格式）
# ==========================================================

# --------  字体  --------
[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

# --------  窗口  --------
[window]
decorations = "none"
opacity     = 0.95

[window.dimensions]
columns = 110
lines   = 30

[window.padding]
x = 12
y = 12

# --------  光标  --------
[cursor]
style            = "Beam"
thickness        = 0.15
unfocused_hollow = true
vi_mode_style    = "None"

# --------  滚动/选择/键盘  --------
[scrolling]
history    = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key    = "Q"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "None"
key    = "W"
mods   = "Control|Shift"

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[colors.normal]
black   = "#414b50"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
